version: '3.9'
services:
  mysql-inventory:
    # the remote image for the version of MySQL that we want
    image: mysql:8
    # always restart whenever it goes down, error or not
    restart: "unless-stopped"
    # map port 3306 on the host to 3306 on the mysql container
    ports:
      - 3306:3306
    expose:
      - 3306
    # exposes environment variables to the container
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./baseline.sql:/docker-entrypoint-initdb.d/baseline.sql
